## sim parameters
sim_len: 30
dt_sim: 0.0001
dt_control: 0.02
wheel_radius : 0.03
robot_width : 0.270
robot_length : 0.270



## motor parameters
motor_gain: 2.16
gain_mismatch: 0
motor_time_constant: 0.1
time_constant_mismatch: 0
measurement_bias: 0
measurement_std: 0
closed_loop_constant: 0.1
max_delta_u : 12
max_u: 12.0
kf_percentage: 0


#MPC
N : 100

Q:
  - [1, 0]
  - [0, 1]

R:
  - [5, 0]
  - [0, 5]
augmented: false

x_trajectory : 'config/x_trajectory2.npy'
y_trajectory : 'config/y_trajectory2.npy'